[build]
publish = "public"
command = "hugo --theme=dimension --buildDrafts --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.62.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --theme=dimension --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.62.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --theme=dimension --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.62.1"

[context.branch-deploy]
command = "hugo --theme=dimension --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.62.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

